name: Enrich Release
on:
  release:
    types: [created]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: bruceadams/get-release@v1.2.1
      id: get_release
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - run: npm --no-git-tag-version version ${{ steps.get_release.outputs.tag_name }}
    - run: npm run ci-release
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ./dist/docs.zip
        asset_name: cube-codes-visualizer-${{ steps.get_release.outputs.tag_name }}-docs.zip
        asset_content_type: application/zip
    - uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ./dist/browser/cube-codes-visualizer.js
        asset_name: cube-codes-visualizer-${{ steps.get_release.outputs.tag_name }}-browser.js
        asset_content_type: application/javascript